version: '2'
services:
  web:
    build: .
    command: cargo run
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      ROCKET_ADDRESS: 0.0.0.0
      ROCKET_PORT: 3000
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: rust_blog
      POSTGRES_DB: rust_blog
