# Except for the secret key, none of these are actually needed; Rocket has sane
# defaults. We show all of them here explicitly for demonstrative purposes.

[global.limits]
forms = 32768
json = 1048576 # this is an extra used by the json contrib module
msgpack = 1048576 # this is an extra used by the msgpack contrib module

[development]
address = "localhost"
port = 8000
workers = 1

[staging]
address = "0.0.0.0"
port = 80
log = "normal"
workers = 8

[production]
address = "0.0.0.0"
port = 80
workers = 12
log = "critical"
